# -*- coding: utf-8 -*-
"""alien.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ps_GEr0EsA5x_fUGv3qjMh-NCwbGoKbp
"""

# Commented out IPython magic to ensure Python compatibility.
#import libs
# %reload_ext autoreload
# %autoreload 2
# %matplotlib inline

from fastai.vision import *
from fastai.metrics import error_rate

help(untar_data)

uploaded = files.upload()

from zipfile import ZipFile

# Create a ZipFile Object and load sample.zip in it
with ZipFile('alien.zip', 'r') as zipObj:
   # Extract all the contents of zip file in current directory
   zipObj.extractall()

path_img = '/data/validation/'

from fastai.metrics import *
fnames = get_image_files(path_img)
fnames[:5]

np.random.seed(2)
pat = r'/([^/]+)_\d+.jpg$'

data = ImageDataBunch.from_name_re(path_img, fnames, pat, ds_tfms=get_transforms(), size=224, bs=bs
                                  ).normalize(imagenet_stats)

data.show_batch(rows=3, figsize=(7,6))

